# Generated by Django 5.0 on 2023-12-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
