# Generated by Django 5.0 on 2023-12-19 01:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wie_app', '0003_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='needs',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
    ]
